export const ROUTES = {
  home: "/",
  landing: "/",
  activateHousehold: "/activate-household",
  dashboard: "/dashboard",
  profiles: "/profiles",
  inventory: "/inventory",
  shopping: "/shopping",
  recipes: "/recipes",
  meals: "/meals",
  tools: "/tools",
  tasks: "/tasks",
  status: "/status",
  capacity: "/capacity",
  pricing: "/pricing",
  subscription: "/subscription",
  readiness: "/readiness",
  householdMembers: "/household/members",
  inviteAccept: "/invite/:token",
  myProfile: "/my-profile",
  selfService: "/self-service",
  integrations: "/integrations",
  adminCatalog: "/admin/catalog",
  notFound: "*",

  HOME: "/",
  LANDING: "/",
  ACTIVATE_HOUSEHOLD: "/activate-household",
  DASHBOARD: "/dashboard",
  PROFILES: "/profiles",
  INVENTORY: "/inventory",
  SHOPPING: "/shopping",
  RECIPES: "/recipes",
  MEALS: "/meals",
  TOOLS: "/meals",
  TASKS: "/tasks",
  STATUS: "/status",
  CAPACITY: "/capacity",
  PRICING: "/pricing",
  SUBSCRIPTION: "/subscription",
  READINESS: "/readiness",
  HOUSEHOLD_MEMBERS: "/household/members",
  INVITE_ACCEPT: "/invite/:token",
  MY_PROFILE: "/my-profile",
  SELF_SERVICE: "/self-service",
  INTEGRATIONS: "/integrations",
  ADMIN_CATALOG: "/admin/catalog",
  NOT_FOUND: "*",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];